In [33]:
import numpy as np

from functions.jem_functions import generate_jem_df
from functions.lims_functions import generate_lims_df
from functions.transcriptomics_functions import generate_test_df, test_mismatch_patch_date, test_miss_lims, test_miss_jem, test_mismatch_specimen, test_mismatch_patch_tube, test_pc_tubes, test_px_tubes, test_lims_structure, test_jem_projects
from functions.file_functions import load_data_variables

In [14]:
jem_df = generate_jem_df("ivscc", "only_patch_tubes")

In [15]:
jem_df

,approach.project_patch_link,approach.sliceHealth,experiment_break_in.auto_break_in,experiment_cell_attached.auto_cell_attached,extraction.autoExtractSuccess,extraction.experiment_auto_extract.autoExtract,extraction.experiment_auto_extract.autoExtractFailure,extraction.experiment_auto_extract.autoExtractGenFailure,extraction.experiment_auto_extract.autoExtractNotes,extraction.experiment_auto_extract.autoExtractStatus,...,jem-date_patch_m,jem-date_patch_d,jem-time_duration_experiment,jem-time_duration_extraction,jem-time_duration_retraction,jem-roi_major,jem-roi_minor,jem-roi_super,jem-status_patch_tube,jem-id_species
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,17,16.02,3.67,5.23,MB,DR,Subcortical,Patch Tube,Mouse
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,17,24.38,4.00,2.83,MB,DR,Subcortical,Patch Tube,Mouse
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,14,15.95,2.57,5.73,MB,DR,Subcortical,Patch Tube,Mouse
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,14,21.08,2.67,3.32,MB,DR,Subcortical,Patch Tube,Mouse
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,14,13.07,3.52,2.90,MB,DR,Subcortical,Patch Tube,Mouse
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,02,12.82,3.03,0.95,OCx,L6,Cortical,Patch Tube,Human
1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,02,15.07,8.18,4.98,OCx,L6,Cortical,Patch Tube,Human
1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,02,19.87,15.17,3.97,OCx,L6,Cortical,Patch Tube,Human
1757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,02,8.17,3.85,0.98,OCx,L6,Cortical,Patch Tube,Human
1758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,02,11.48,4.03,2.93,OCx,L6,Cortical,Patch Tube,Human

In [16]:
sorted(list(jem_df.columns))

['approach.project_patch_link',
 'approach.sliceHealth',
 'experiment_break_in.auto_break_in',
 'experiment_cell_attached.auto_cell_attached',
 'extraction.autoExtractSuccess',
 'extraction.experiment_auto_extract.autoExtract',
 'extraction.experiment_auto_extract.autoExtractFailure',
 'extraction.experiment_auto_extract.autoExtractGenFailure',
 'extraction.experiment_auto_extract.autoExtractNotes',
 'extraction.experiment_auto_extract.autoExtractStatus',
 'extraction.experiment_auto_extract.autoExtractTechFailure',
 'extraction.experiment_auto_extract.autoNucProfile',
 'extraction.extractionObservations',
 'extraction.nucleus_auto_extract.autoExtract',
 'extraction.nucleus_auto_extract.autoExtractFailure',
 'extraction.nucleus_auto_extract.autoExtractGenFailure',
 'extraction.nucleus_auto_extract.autoExtractNotes',
 'extraction.nucleus_auto_extract.autoExtractStatus',
 'extraction.nucleus_auto_extract.autoExtractTechFailure',
 'extraction.nucleus_auto_extract.autoNucProfile',
 'extraction.pilotNameExtra',
 'extraction.sampleObservations',
 'extraction.timeRetractionStart',
 'failureNotes',
 'flipped',
 'jem-acsf_type',
 'jem-auto_extract_failure_type',
 'jem-auto_extract_general_failure',
 'jem-auto_extract_status',
 'jem-auto_extract_tech_failure',
 'jem-auto_extraction',
 'jem-auto_extraction_notes',
 'jem-auto_extraction_profile',
 'jem-automation',
 'jem-break_in_pressure_max',
 'jem-break_in_reseal',
 'jem-break_in_status',
 'jem-break_in_status_failure',
 'jem-break_in_time_end',
 'jem-break_in_time_start',
 'jem-break_in_zap_max',
 'jem-break_in_zap_use',
 'jem-cell_attached_dimple',
 'jem-cell_attached_status',
 'jem-cell_attached_status_failure',
 'jem-cell_health',
 'jem-cell_virus_enhancer',
 'jem-date_acsf',
 'jem-date_blank',
 'jem-date_internal',
 'jem-date_patch',
 'jem-date_patch_d',
 'jem-date_patch_m',
 'jem-date_patch_y',
 'jem-date_patch_y-m-d',
 'jem-depth',
 'jem-dic',
 'jem-health_fill_quality',
 'jem-hyp_cell_type',
 'jem-id_cell_specimen',
 'jem-id_patched_cell_container',
 'jem-id_rig_number',
 'jem-id_rig_user',
 'jem-id_slice_specimen',
 'jem-id_species',
 'jem-in_bath_clog',
 'jem-in_bath_resistance',
 'jem-in_bath_time_start',
 'jem-notes_extraction',
 'jem-notes_failure',
 'jem-notes_overall',
 'jem-notes_qc',
 'jem-nucleus_post_patch',
 'jem-nucleus_sucked',
 'jem-pipette_cleaned',
 'jem-pressure_extraction',
 'jem-pressure_retraction',
 'jem-project_level_nucleus',
 'jem-project_name',
 'jem-res_final_seal',
 'jem-roi_major',
 'jem-roi_major_minor',
 'jem-roi_minor',
 'jem-roi_super',
 'jem-seal_time_start',
 'jem-slice_health',
 'jem-slice_level_project',
 'jem-slice_observations',
 'jem-slice_quality_comments',
 'jem-status_attempt',
 'jem-status_misinformation',
 'jem-status_patch_tube',
 'jem-status_reporter',
 'jem-status_success_failure',
 'jem-stimulus_set',
 'jem-time_duration_experiment',
 'jem-time_duration_extraction',
 'jem-time_duration_retraction',
 'jem-time_exp_channel_end',
 'jem-time_exp_extraction_end',
 'jem-time_exp_extraction_start',
 'jem-time_exp_retraction_end',
 'jem-time_patch',
 'jem-time_slice_eval',
 'jem-version_jem_form',
 'jem-virus_enhancer',
 'jem-visible_nucleus',
 'jem_created',
 'sliceQuality']

In [17]:
[f for f in jem_df['jem-id_cell_specimen'] if f.startswith('H26.51.001.11.04')]

['H26.51.001.11.04.01', 'H26.51.001.11.04.02', 'H26.51.001.11.04.03']

In [18]:
from functions.transcriptomics_functions import generate_last_business_day, user_prompts_daily

# last_bday, last_bday_str = generate_last_business_day()
last_bday = 260114
last_bday_str = str(last_bday)

# User prompts
# date_report, dt_report = user_prompts_daily(last_bday_str, last_bday_str)

In [19]:
date_report = "260114"

lims_df = generate_lims_df("ivscc", last_bday_str)

In [20]:
import pandas as pd
# Merge dataframes by outer join based on specimen id 
jem_lims_name_df = pd.merge(left=jem_df, right=lims_df, left_on="jem-id_cell_specimen", right_on="lims-id_cell_specimen", how="outer")
# Merge dataframes by outer join based on patch tube 
jem_lims_tube_df = pd.merge(left=jem_df, right=lims_df, left_on="jem-id_patched_cell_container", right_on="lims-id_patched_cell_container", how="outer")

In [21]:
jem_lims_name_df

,approach.project_patch_link,approach.sliceHealth,experiment_break_in.auto_break_in,experiment_cell_attached.auto_cell_attached,extraction.autoExtractSuccess,extraction.experiment_auto_extract.autoExtract,extraction.experiment_auto_extract.autoExtractFailure,extraction.experiment_auto_extract.autoExtractGenFailure,extraction.experiment_auto_extract.autoExtractNotes,extraction.experiment_auto_extract.autoExtractStatus,...,lims-depth,lims-histology_well_name,lims-id_cell_specimen_id,lims-id_slice_genotype,lims-id_slice_specimen,lims-id_species,lims-id_project_code,lims-structure,lims-cell_reporter,lims-exclude_container
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
[f for f in jem_lims_name_df['jem-id_cell_specimen'] if f.startswith('H26.51.001.11.04')]

['H26.51.001.11.04.01', 'H26.51.001.11.04.02', 'H26.51.001.11.04.03']

In [23]:
jem_lims_name_df['jem-id_cell_specimen'].unique()

array(['C57BL6J-839149.04.09.01', 'C57BL6J-839149.04.09.02',
       'Pvalb-IRES-Cre;Ai14-830327.02.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.02.09.03',
       'Pvalb-IRES-Cre;Ai14-830327.02.09.04', 'QN25.26.029.15.11.03',
       'Pvalb-IRES-Cre;Ai14-828949.14.03.02',
       'Sst-IRES-Cre;Ai14-833441.07.13.01', 'C57BL6J-837955.09.14.01',
       'QF25.26.019.15m.03.01', 'QF25.26.019.15m.03.02',
       'QF25.26.019.15m.03.03', 'QF25.26.019.15m.03.04',
       'H25.51.018.11.03.01', 'H25.51.018.11.03.02',
       'Pvalb-IRES-Cre;Ai14-830325.11.04.01', 'C57BL6J-837954.08.09.01',
       'C57BL6J-837954.08.09.02', 'C57BL6J-839151.03.09.01',
       'C57BL6J-839151.03.09.02', 'QN26.26.002.15.02.01',
       'QN26.26.002.15.02.03', 'QN26.26.002.15.02.04',
       'QN25.26.026.16.06.01', 'QN25.26.026.16.06.02',
       'QN25.26.026.16.06.03', 'QN25.26.026.16.06.05',
       'Pvalb-IRES-Cre;Ai14-830327.05.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.05.09.02', 'H25.51.018.11.53.01',
       'H25.51.018.11.53.03', 'H25.51.018.11.53.04',
       'H25.51.018.11.53.05', 'H25.51.018.11.53.06',
       'H25.51.018.11.53.07', 'C57BL6J-823514.08.13.02',
       'C57BL6J-823514.08.13.03', 'QN26.26.003.15.17.01',
       'QN26.26.003.15.17.02', 'QN26.26.003.15.17.03',
       'QN26.26.003.15.17.04', 'QN26.26.003.15.17.05',
       'Sst-IRES-Cre;Ai14-822449.08.11.01',
       'Sst-IRES-Cre;Ai14-822449.08.11.02', 'QF25.26.024.14v.05.01',
       'QF25.26.024.14v.05.02', 'H25.51.016.11.53.01',
       'H25.51.016.11.53.04', 'H25.51.016.11.53.05',
       'H25.51.016.11.53.07', 'H25.51.016.11.53.08',
       'QF25.26.024.14v.02.01', 'QF25.26.024.14v.02.02',
       'Sst-IRES-Cre;Ai14-822449.07.11.01',
       'Sst-IRES-Cre;Ai14-822449.07.11.02',
       'Sst-IRES-Cre;Ai14-833442.06.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.03',
       'C57BL6J-837954.03.09.01', 'Pvalb-IRES-Cre;Ai14-828949.15.04.01',
       'Pvalb-IRES-Cre;Ai14-828949.15.04.03',
       'Sst-IRES-Cre;Ai14-833444.10.13.01', 'C57BL6J-839148.03.09.02',
       'C57BL6J-839148.03.09.03', 'Gad2-IRES-Cre;Ai14-841407.13.04.01',
       'Sst-IRES-Cre;Ai14-833444.09.13.01',
       'Vip-IRES-Cre-835274.13.03.01',
       'Sst-IRES-Cre;Ai14-833441.12.13.01',
       'Sst-IRES-Cre;Ai14-833441.12.13.02', 'C57BL6J-837954.02.09.01',
       'C57BL6J-837954.02.09.02', 'C57BL6J-837954.02.09.03',
       'C57BL6J-837954.02.09.04', 'C57BL6J-837954.02.09.05',
       'QF25.26.023.15m.14.01', 'QF25.26.023.15m.14.02',
       'QF25.26.023.15m.14.03', 'QF25.26.023.15m.14.05',
       'QF25.26.024.14v.03.01', 'QF25.26.024.14v.03.02',
       'QF25.26.024.14v.03.03', 'QN26.26.002.15.04.01',
       'QN26.26.002.15.04.02', 'QN26.26.002.15.04.03',
       'C57BL6J-839151.04.09.01', 'Drd1a-Cre;Oi9-820240.04.10.01',
       'Drd1a-Cre;Oi9-820240.04.10.02', 'QF25.26.023.15m.11.01',
       'QF25.26.023.15m.11.02', 'Sst-IRES-Cre;Ai14-822449.11.11.01',
       'QF25.26.023.15m.12.01', 'QF25.26.023.15m.12.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.03',
       'C57BL6J-815107.05.03.01', 'Scn1a-R613X_B6-830129.04.09.01',
       'Scn1a-R613X_B6-830129.04.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.04',
       'QN25.26.017.15m.06.01.01', 'QN25.26.017.15m.06.01.02',
       'QN25.26.017.15m.06.01.03', 'QN26.26.003.15.10.01',
       'QN26.26.003.15.10.03', 'C57BL6J-837955.14.13.01',
       'H25.51.018.11.54.01', 'H25.51.018.11.54.02',
       'H25.51.018.11.54.03', 'H25.51.018.11.54.04',
       'H25.51.018.11.54.05', 'H25.51.018.11.54.06',
       'H25.51.018.11.54.07', 'QN26.26.003.15.06.01',
       'H26.51.001.11.03.01', 'H26.51.001.11.03.02',
       'H26.51.001.11.03.03', 'H26.51.001.11.03.04',
       'C57BL6J-837954.04.09.01', 'Drd1a-Cre;Oi9-820240.06.11.01',
       'Drd1a-Cre;Oi9-820240.06.11.02', 'Drd1a-Cre;Oi9-820240.06.11.03',
       'QF25.26.019.15m.05.01', 'QF25.26.019.15m.05.02',
       'QF25.26.019.15m.05.04', 'QN25.26.018.15m.10.01.02',
       'QN25.26.018.15m.10.01.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827267.11.13.02',
       'QN25.26.018.15m.11.01.01', 'QN25.26.018.15m.11.01.02',
       'QN25.26.018.15m.11.01.03', 'QN25.26.018.15m.11.01.04',
       'QN25.26.018.15m.11.01.05', 'H25.51.018.11.02.01',
       'H25.51.018.11.02.02', 'H25.51.018.11.02.04',
       'H25.51.018.11.02.05', 'Scn1a-R613X_B6-830129.06.09.01',
       'Scn1a-R613X_B6-830129.06.09.04',
       'Gad2-IRES-Cre;Ai14-841410.16.03.01', 'QF25.26.019.15m.04.01',
       'QF25.26.019.15m.04.03', 'QF25.26.022.15m.05.01',
       'QF25.26.022.15m.05.02', 'QF25.26.022.15m.05.03',
       'QF25.26.022.15m.05.04', 'QN26.26.002.16.02B.02',
       'Gad2-IRES-Cre;Ai14-841407.14.03.01',
       'Gad2-IRES-Cre;Ai14-841407.14.03.02',
       'Gad2-IRES-Cre;Ai14-841407.14.03.03',
       'Gad2-IRES-Cre;Ai14-841407.14.03.04',
       'Gad2-IRES-Cre;Ai14-841407.14.03.05', 'QF25.26.028.14d.01.02',
       'QF25.26.028.14d.01.03', 'QF25.26.028.14d.01.04',
       'QN25.26.020.15m.04.03', 'C57BL6J-837955.04.13.01',
       'QF25.26.021.15m.06.01', 'QF25.26.021.15m.06.02',
       'QF25.26.021.15m.06.03', 'QF25.26.023.15m.06.03',
       'QF25.26.023.15m.06.04', 'H26.51.001.11.54.01',
       'H26.51.001.11.54.02', 'H26.51.001.11.54.03',
       'H26.51.001.11.54.05', 'H26.51.001.11.54.07',
       'H26.51.001.11.54.08', 'H26.51.001.11.54.09',
       'Gad2-IRES-Cre;Ai14-841408.13.13.01',
       'Gad2-IRES-Cre;Ai14-841408.13.13.02',
       'Vip-IRES-Cre-835274.14.03.01', 'Vip-IRES-Cre-835274.14.03.02',
       'Vip-IRES-Cre-835274.14.03.03',
       'Gad2-IRES-Cre;Ai14-841409.05.01.01',
       'Gad2-IRES-Cre;Ai14-841409.05.01.02', 'QN25.26.017.15m.05.01.01',
       'QN25.26.017.15m.05.01.03', 'QN25.26.017.15m.05.01.04',
       'QN25.26.017.15m.05.01.05', 'QN25.26.017.15m.05.01.06',
       'QN25.26.026.16.10.01', 'QN25.26.026.16.10.02',
       'QN25.26.026.16.10.03', 'QN25.26.026.16.10.04',
       'H25.51.016.11.55.02', 'H25.51.016.11.55.03',
       'H25.51.016.11.55.05', 'QF25.26.023.15m.13.03',
       'H25.51.017.11.52.01', 'H25.51.017.11.52.02',
       'QF25.26.016.15m.13.01.01', 'QF25.26.016.15m.13.01.02',
       'Pvalb-IRES-Cre;Ai14-830325.10.03.01',
       'Pvalb-IRES-Cre;Ai14-830325.10.03.02',
       'Pvalb-IRES-Cre;Ai14-830325.10.03.03',
       'Sst-IRES-Cre;Ai14-833443.12.13.01',
       'Sst-IRES-Cre;Ai14-833443.12.13.02',
       'Drd1a-Cre;Oi9-820240.05.11.02', 'C57BL6J-837955.11.13.01',
       'QF25.26.024.14d.02.01', 'QF25.26.024.14d.02.02',
       'QF25.26.028.14v.08.01', 'QF25.26.028.14v.08.02',
       'H25.51.015.11.54.01.01', 'H25.51.015.11.54.01.04',
       'QN26.26.002.15.05.01', 'QN26.26.002.15.05.02',
       'QN26.26.002.15.05.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.07.13.01',
       'H25.51.016.11.04.01', 'H25.51.016.11.04.02',
       'H25.51.016.11.04.03', 'H25.51.016.11.04.04',
       'H25.51.016.11.04.05', 'H25.51.016.11.04.06',
       'Gad2-IRES-Cre;Ai14-841406.04.09.01',
       'Gad2-IRES-Cre;Ai14-841406.04.09.02',
       'Drd1a-Cre;Oi9-813175.07.10.01', 'Drd1a-Cre;Oi9-813175.07.10.03',
       'Drd1a-Cre;Oi9-813175.08.10.02', 'Drd1a-Cre;Oi9-813175.08.10.03',
       'QF25.26.016.15m.09.01.01', 'QF25.26.016.15m.09.01.02',
       'QF25.26.016.15m.09.01.03', 'QN26.26.004.15.06.01',
       'QN26.26.004.15.06.02', 'QN26.26.004.15.06.03',
       'QN26.26.002.15.11.03', 'C57BL6J-823514.09.13.01',
       'C57BL6J-823514.09.13.02', 'C57BL6J-823514.09.13.03',
       'C57BL6J-837954.01.09.01', 'C57BL6J-837954.01.09.02',
       'QF25.26.019.15m.02.01', 'QF25.26.019.15m.02.02',
       'QF25.26.019.15m.02.03', 'QF25.26.019.15m.02.04',
       'QF25.26.019.15m.02.05', 'QF25.26.021.15m.05.01',
       'QF25.26.021.15m.05.02', 'QF25.26.021.15m.05.04',
       'Scn1a-R613X_B6-830133.06.01.02', 'C57BL6J-815107.05.04.02',
       'QN26.26.004.15.04.01', 'QN26.26.004.15.04.02',
       'QN26.26.004.15.04.03', 'H25.51.018.11.51.01',
       'H25.51.018.11.51.02', 'H25.51.018.11.51.03',
       'H25.51.018.11.51.04', 'H25.51.018.11.51.05',
       'H25.51.018.11.51.06', 'H25.51.018.11.51.07',
       'QF25.26.028.14v.10.02', 'QF25.26.028.14v.10.03',
       'QF25.26.028.14v.10.04', 'QF25.26.028.14v.10.05',
       'Sst-IRES-Cre;Ai14-833440.10.14.03', 'C57BL6J-823516.02.09.01',
       'C57BL6J-823516.02.09.03', 'QF25.26.028.14d.04.01',
       'QF25.26.028.14d.04.02', 'C57BL6J-823513.09.13.01',
       'C57BL6J-823513.09.13.02', 'C57BL6J-823513.09.13.03',
       'H26.51.001.11.52.01', 'H26.51.001.11.52.02',
       'H26.51.001.11.52.03', 'H26.51.001.11.52.04',
       'H26.51.001.11.52.05', 'H26.51.001.11.52.06',
       'Pvalb-IRES-Cre;Ai14-830327.06.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.06.09.02',
       'Pvalb-IRES-Cre;Ai14-830327.06.09.03', 'QF25.26.024.14v.01.01',
       'QF25.26.024.14v.01.03', 'QF25.26.024.14v.01.04',
       'C57BL6J-823513.12.13.01', 'C57BL6J-823515.04.09.03',
       'C57BL6J-823515.04.09.05', 'C57BL6J-823515.04.09.06',
       'Drd1a-Cre;Oi9-813175.05.10.01', 'Drd1a-Cre;Oi9-813175.05.10.02',
       'QF25.26.019.15m.01.01', 'QF25.26.019.15m.01.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827265.11.13.01',
       'C57BL6J-837954.06.09.01', 'H25.51.017.11.56.02',
       'H25.51.017.11.56.03', 'H25.51.016.11.05.01',
       'H25.51.016.11.05.02', 'H25.51.016.11.05.03',
       'H25.51.016.11.05.04', 'H25.51.016.11.05.05',
       'H25.51.016.11.05.06', 'H25.51.016.11.05.07',
       'H25.51.016.11.05.08', 'Gad2-IRES-Cre;Ai14-841410.16.04.02',
       'Gad2-IRES-Cre;Ai14-841410.16.04.03',
       'Gad2-IRES-Cre;Ai14-841410.16.04.04', 'C57BL6J-823514.12.13.01',
       'C57BL6J-823514.12.13.02', 'C57BL6J-823514.12.13.03',
       'C57BL6J-823514.12.13.04', 'Sst-IRES-Cre;Ai14-833439.07.13.01',
       'C57BL6J-823514.11.13.01', 'C57BL6J-823514.11.13.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.13.13.02',
       'C57BL6J-837957.04.09.01', 'C57BL6J-837957.04.09.02',
       'H25.51.016.11.54.01', 'H25.51.016.11.54.02',
       'H25.51.016.11.54.03', 'H25.51.016.11.54.04',
       'H25.51.016.11.54.05', 'QN26.26.002.15.03.02',
       'Scn1a-R613X_B6-830133.04.01.01', 'Scn1a-R613X_B6-830133.04.01.03',
       'Sst-IRES-Cre;Ai14-833440.12.13.01',
       'Sst-IRES-Cre;Ai14-833440.12.13.02',
       'Sst-IRES-Cre;Ai14-833440.12.13.03',
       'Pvalb-IRES-Cre;Ai14-830327.04.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.04.09.04',
       'Pvalb-IRES-Cre;Ai14-830327.04.09.05',
       'Gad2-IRES-Cre;Ai14-841406.03.09.01',
       'Gad2-IRES-Cre;Ai14-841406.03.09.02',
       'Gad2-IRES-Cre;Ai14-841406.03.09.03',
       'Drd1a-Cre;Oi9-820240.04.11.03', 'C57BL6J-823513.07.13.01',
       'Sst-IRES-Cre;Ai14-833442.04.09.01',
       'Sst-IRES-Cre;Ai14-833442.04.09.02',
       'Sst-IRES-Cre;Ai14-833442.04.09.03',
       'Sst-IRES-Cre;Ai14-833444.13.14.01', 'QN25.26.026.16.12.01',
       'QN25.26.026.16.12.02', 'QN25.26.026.16.12.03',
       'QN25.26.026.16.12.04', 'QF25.26.023.15m.07.01',
       'QF25.26.023.15m.07.03', 'QF25.26.023.15m.07.05',
       'QF25.26.023.15m.07.06', 'QF25.26.023.15m.07.07',
       'C57BL6J-839148.05.09.01', 'C57BL6J-839148.05.09.02',
       'C57BL6J-839148.05.09.03', 'C57BL6J-839148.05.09.04',
       'Gad2-IRES-Cre;Ai14-841407.14.04.01',
       'Gad2-IRES-Cre;Ai14-841407.14.04.02', 'C57BL6J-837957.03.09.01',
       'C57BL6J-837954.07.09.01', 'C57BL6J-837954.07.09.02',
       'QN25.26.029.15.07.02', 'Sst-IRES-Cre;Ai14-833439.11.13.01',
       'Sst-IRES-Cre;Ai14-833439.11.13.02',
       'Sst-IRES-Cre;Ai14-833439.11.13.03',
       'Vip-IRES-Cre-835276.17.04.01', 'Vip-IRES-Cre-835276.17.04.02',
       'Vip-IRES-Cre-835276.17.04.03', 'Vip-IRES-Cre-835276.17.04.04',
       'Pvalb-IRES-Cre;Ai14-830327.03.09.02',
       'Pvalb-IRES-Cre;Ai14-830327.03.09.03',
       'Pvalb-IRES-Cre;Ai14-830327.03.09.05', 'QN26.26.003.15.08.02',
       'QF25.26.023.15m.04.02', 'QF25.26.023.15m.04.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.15.13.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.15.13.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.15.13.03',
       'C57BL6J-815107.06.03.01', 'C57BL6J-815107.06.03.03',
       'C57BL6J-815107.06.03.05', 'C57BL6J-815107.06.03.06',
       'Sst-IRES-Cre;Ai14-833444.16.13.01',
       'Sst-IRES-Cre;Ai14-833443.11.13.01',
       'Sst-IRES-Cre;Ai14-833443.11.13.02', 'QF25.26.016.15m.06.01.01',
       'QF25.26.016.15m.06.01.02', 'QF25.26.016.15m.06.01.03',
       'H25.51.016.11.06.01', 'H25.51.016.11.06.02',
       'H25.51.016.11.06.03', 'H25.51.016.11.06.04',
       'QF25.26.028.14d.03.01', 'QF25.26.028.14d.03.02',
       'QF25.26.028.14d.03.03', 'Vip-IRES-Cre-835276.15.04.01',
       'Vip-IRES-Cre-835276.15.04.02', 'Drd1a-Cre;Oi9-820240.06.10.01',
       'Scn1a-R613X_B6-830133.03.01.01', 'Scn1a-R613X_B6-830133.03.01.02',
       'H25.51.017.11.57.01', 'H25.51.017.11.57.02',
       'H25.51.017.11.57.04', 'H25.51.017.11.57.05',
       'H25.51.017.11.57.06', 'H25.51.017.11.57.07',
       'H25.51.017.11.57.08', 'H25.51.017.11.57.09',
       'H25.51.017.11.57.10', 'H25.51.017.11.57.11',
       'QN26.26.002.16.02A.02', 'QN26.26.002.16.02A.03',
       'QN26.26.002.16.02A.04', 'QN26.26.002.16.02A.05',
       'QN25.26.018.15m.09.01.01', 'QN25.26.018.15m.09.01.03',
       'QN26.26.003.15.15.01', 'QN26.26.003.15.15.02',
       'QN26.26.003.15.15.03', 'QN26.26.003.15.15.04',
       'QN26.26.003.15.15.05', 'QF25.26.016.15m.11.01.01',
       'H25.51.016.11.07.01', 'H25.51.016.11.07.02',
       'H25.51.016.11.07.03', 'H25.51.016.11.07.04',
       'H25.51.016.11.07.05', 'H25.51.016.11.07.06',
       'H25.51.016.11.07.07', 'QN25.26.020.15m.01.01',
       'Gad2-IRES-Cre;Ai14-841407.13.03.01',
       'Gad2-IRES-Cre;Ai14-841407.13.03.02',
       'Gad2-IRES-Cre;Ai14-841407.13.03.03',
       'Vip-IRES-Cre-835276.16.03.01', 'Vip-IRES-Cre-835276.16.03.02',
       'Drd1a-Cre;Oi9-820239.06.10.01', 'Drd1a-Cre;Oi9-820239.06.10.02',
       'Drd1a-Cre;Oi9-820239.06.10.03', 'Drd1a-Cre;Oi9-820239.06.10.04',
       'Drd1a-Cre;Oi9-820239.06.10.05', 'QN26.26.002.15.10.01',
       'QN26.26.002.15.10.02', 'QN26.26.002.15.10.03',
       'QN26.26.002.15.10.04', 'QN26.26.002.15.10.05',
       'Vip-IRES-Cre-835274.11.03.01', 'QN25.26.026.16.13.01',
       'QN25.26.026.16.13.02', 'QN25.26.026.16.13.03',
       'QN25.26.026.16.13.04', 'QN25.26.026.16.13.05',
       'QN25.26.029.15.12.01', 'QN25.26.029.15.12.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.06.14.01',
       'Vip-IRES-Cre-835274.15.03.01', 'Vip-IRES-Cre-835274.15.03.02',
       'Vip-IRES-Cre-835274.15.03.03',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.01',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.02',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.03',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.05',
       'Sst-IRES-Cre;Ai14-833439.10.14.01',
       'Sst-IRES-Cre;Ai14-833441.14.14.02', 'QN25.26.029.15.14.02',
       'QN25.26.029.15.14.03', 'Vip-IRES-Cre-835276.15.03.01',
       'H25.51.016.11.52.03', 'H25.51.016.11.52.05',
       'QN25.26.018.15m.04.01.01', 'QN25.26.018.15m.04.01.02',
       'Scn1a-R613X_B6-830133.05.01.02', 'Scn1a-R613X_B6-830133.05.01.03',
       'Scn1a-R613X_B6-830133.05.01.04', 'QF25.26.019.15m.12.01',
       'QF25.26.019.15m.12.02', 'QF25.26.019.15m.12.03',
       'QF25.26.019.15m.12.04', 'QF25.26.019.15m.12.05',
       'QF25.26.019.15m.12.06', 'QF25.26.019.15m.12.07',
       'C57BL6J-839149.02.09.01', 'C57BL6J-839149.02.09.02',
       'C57BL6J-839149.02.09.03', 'C57BL6J-839149.02.09.04',
       'C57BL6J-823513.10.13.01', 'QF25.26.024.14v.04.02',
       'QF25.26.024.14v.04.03', 'Pvalb-IRES-Cre;Ai14-830325.09.03.01',
       'Pvalb-IRES-Cre;Ai14-830325.09.03.02',
       'Pvalb-IRES-Cre;Ai14-830325.09.03.03',
       'Pvalb-IRES-Cre;Ai14-830325.09.03.04',
       'Gad2-IRES-Cre;Ai14-841409.03.02.01', 'QF25.26.019.15m.11.01',
       'QF25.26.019.15m.11.02', 'QF25.26.019.15m.11.03',
       'QF25.26.019.15m.11.04', 'QF25.26.019.15m.11.05',
       'H25.51.017.11.54.01', 'C57BL6J-839148.04.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.08.13.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.08.13.02',
       'Sst-IRES-Cre;Ai14-822449.06.12.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.05.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.05.09.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.05.09.04',
       'C57BL6J-837955.10.13.01', 'QN25.26.017.15m.04.01.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.04',
       'H26.51.001.11.51.01', 'H26.51.001.11.51.02',
       'H26.51.001.11.51.04', 'H26.51.001.11.51.05',
       'Gad2-IRES-Cre;Ai14-841406.02.09.01',
       'Gad2-IRES-Cre;Ai14-841406.02.09.02',
       'Gad2-IRES-Cre;Ai14-841406.02.09.03', 'QF25.26.023.15m.09.02',
       'Scn1a-R613X_B6-830129.03.09.01', 'H26.06.351.11.04.01',
       'H25.51.017.11.51.01', 'H25.51.017.11.51.02',
       'H25.51.017.11.51.03', 'H25.51.017.11.51.04',
       'H25.51.017.11.51.05', 'H25.51.017.11.51.06',
       'QF25.26.024.15m.07.01', 'QF25.26.024.15m.07.05',
       'QF25.26.021.15m.10.01', 'H25.51.015.11.55.01.01',
       'H25.51.015.11.55.01.02', 'H25.51.015.11.55.01.04',
       'C57BL6J-837957.05.09.01', 'C57BL6J-837957.05.09.03',
       'Gad2-IRES-Cre;Ai14-841410.17.04.01', 'C57BL6J-823514.14.13.01',
       'H25.51.018.11.52.01', 'H25.51.018.11.52.02',
       'H25.51.018.11.52.03', 'H25.51.018.11.52.04',
       'H25.51.018.11.52.05', 'H25.51.018.11.52.06',
       'H25.51.018.11.52.07', 'Drd1a-Cre;Oi9-820240.05.10.01',
       'QN25.26.017.15m.07.01.02', 'QF25.26.019.16.02A.01',
       'QN26.26.003.15.09.01', 'QN26.26.003.15.09.02',
       'QN26.26.003.15.09.04', 'QN26.26.003.15.09.05',
       'Gad2-IRES-Cre;Ai14-841410.17.03.02',
       'Gad2-IRES-Cre;Ai14-841410.17.03.03', 'C57BL6J-815107.04.04.01',
       'C57BL6J-815107.04.04.02', 'C57BL6J-815107.04.04.03',
       'C57BL6J-815107.04.04.04', 'Gad2-IRES-Cre;Ai14-841408.12.13.01',
       'Gad2-IRES-Cre;Ai14-841408.12.13.02',
       'Gad2-IRES-Cre;Ai14-841408.12.13.03',
       'Gad2-IRES-Cre;Ai14-841408.12.13.04', 'QN26.26.002.15.12.01',
       'QN26.26.002.15.12.02', 'QN26.26.002.15.12.03',
       'H25.51.017.11.53.01', 'H25.51.017.11.53.02',
       'Drd1a-Cre;Oi9-813175.06.10.01', 'Drd1a-Cre;Oi9-813175.06.10.02',
       'Drd1a-Cre;Oi9-813175.06.10.03', 'Drd1a-Cre;Oi9-813175.06.10.04',
       'QF25.26.022.15m.06.01', 'QF25.26.022.15m.06.02',
       'Sst-IRES-Cre;Ai14-833443.07.14.01',
       'Sst-IRES-Cre;Ai14-833443.07.14.02',
       'Sst-IRES-Cre;Ai14-833443.07.14.03', 'QF25.26.022.15m.13.02',
       'Gad2-IRES-Cre;Ai14-841407.12.03.02',
       'Gad2-IRES-Cre;Ai14-841407.12.04.01',
       'Gad2-IRES-Cre;Ai14-841407.12.04.03', 'C57BL6J-837954.05.09.01',
       'C57BL6J-837954.05.09.02', 'QN26.26.003.15.07.01',
       'H25.51.018.11.01.01', 'H25.51.018.11.01.02',
       'H25.51.018.11.01.03', 'H25.51.018.11.01.04',
       'Drd1a-Cre;Oi9-820239.07.10.03', 'Drd1a-Cre;Oi9-820239.07.10.04',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.04.09.01',
       'H26.51.001.11.04.01', 'H26.51.001.11.04.02',
       'H26.51.001.11.04.03', 'H26.51.001.11.05.01',
       'H26.51.001.11.05.02', 'H25.51.016.11.51.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.05',
       'C57BL6J-823513.09.14.01', 'C57BL6J-815107.06.04.03',
       'C57BL6J-815107.06.04.04', 'H25.51.017.11.59.01',
       'QF25.26.024.14d.01.01', 'C57BL6J-837955.12.13.01',
       'QF25.26.024.15m.01.01', 'H25.51.017.11.62.01',
       'H25.51.017.11.62.03', 'H25.51.017.11.62.04',
       'H25.51.017.11.62.05', 'H25.51.017.11.62.06'], dtype=object)

In [24]:
jem_lims_tube_df['jem-id_cell_specimen'].unique()

array(['C57BL6J-839149.04.09.01', 'C57BL6J-839149.04.09.02',
       'Pvalb-IRES-Cre;Ai14-830327.02.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.02.09.03',
       'Pvalb-IRES-Cre;Ai14-830327.02.09.04', 'QN25.26.029.15.11.03',
       'Pvalb-IRES-Cre;Ai14-828949.14.03.02',
       'Sst-IRES-Cre;Ai14-833441.07.13.01', 'C57BL6J-837955.09.14.01',
       'QF25.26.019.15m.03.01', 'QF25.26.019.15m.03.02',
       'QF25.26.019.15m.03.03', 'QF25.26.019.15m.03.04',
       'H25.51.018.11.03.01', 'H25.51.018.11.03.02',
       'Pvalb-IRES-Cre;Ai14-830325.11.04.01', 'C57BL6J-837954.08.09.01',
       'C57BL6J-837954.08.09.02', 'C57BL6J-839151.03.09.01',
       'C57BL6J-839151.03.09.02', 'QN26.26.002.15.02.01',
       'QN26.26.002.15.02.03', 'QN26.26.002.15.02.04',
       'QN25.26.026.16.06.01', 'QN25.26.026.16.06.02',
       'QN25.26.026.16.06.03', 'QN25.26.026.16.06.05',
       'Pvalb-IRES-Cre;Ai14-830327.05.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.05.09.02', 'H25.51.018.11.53.01',
       'H25.51.018.11.53.03', 'H25.51.018.11.53.04',
       'H25.51.018.11.53.05', 'H25.51.018.11.53.06',
       'H25.51.018.11.53.07', 'C57BL6J-823514.08.13.02',
       'C57BL6J-823514.08.13.03', 'QN26.26.003.15.17.01',
       'QN26.26.003.15.17.02', 'QN26.26.003.15.17.03',
       'QN26.26.003.15.17.04', 'QN26.26.003.15.17.05',
       'Sst-IRES-Cre;Ai14-822449.08.11.01',
       'Sst-IRES-Cre;Ai14-822449.08.11.02', 'QF25.26.024.14v.05.01',
       'QF25.26.024.14v.05.02', 'H25.51.016.11.53.01',
       'H25.51.016.11.53.04', 'H25.51.016.11.53.05',
       'H25.51.016.11.53.07', 'H25.51.016.11.53.08',
       'QF25.26.024.14v.02.01', 'QF25.26.024.14v.02.02',
       'Sst-IRES-Cre;Ai14-822449.07.11.01',
       'Sst-IRES-Cre;Ai14-822449.07.11.02',
       'Sst-IRES-Cre;Ai14-833442.06.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.03',
       'C57BL6J-837954.03.09.01', 'Pvalb-IRES-Cre;Ai14-828949.15.04.01',
       'Pvalb-IRES-Cre;Ai14-828949.15.04.03',
       'Sst-IRES-Cre;Ai14-833444.10.13.01', 'C57BL6J-839148.03.09.02',
       'C57BL6J-839148.03.09.03', 'Gad2-IRES-Cre;Ai14-841407.13.04.01',
       'Sst-IRES-Cre;Ai14-833444.09.13.01',
       'Vip-IRES-Cre-835274.13.03.01',
       'Sst-IRES-Cre;Ai14-833441.12.13.01',
       'Sst-IRES-Cre;Ai14-833441.12.13.02', 'C57BL6J-837954.02.09.01',
       'C57BL6J-837954.02.09.02', 'C57BL6J-837954.02.09.03',
       'C57BL6J-837954.02.09.04', 'C57BL6J-837954.02.09.05',
       'QF25.26.023.15m.14.01', 'QF25.26.023.15m.14.02',
       'QF25.26.023.15m.14.03', 'QF25.26.023.15m.14.05',
       'QF25.26.024.14v.03.01', 'QF25.26.024.14v.03.02',
       'QF25.26.024.14v.03.03', 'QN26.26.002.15.04.01',
       'QN26.26.002.15.04.02', 'QN26.26.002.15.04.03',
       'C57BL6J-839151.04.09.01', 'Drd1a-Cre;Oi9-820240.04.10.01',
       'Drd1a-Cre;Oi9-820240.04.10.02', 'QF25.26.023.15m.11.01',
       'QF25.26.023.15m.11.02', 'Sst-IRES-Cre;Ai14-822449.11.11.01',
       'QF25.26.023.15m.12.01', 'QF25.26.023.15m.12.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.03',
       'C57BL6J-815107.05.03.01', 'Scn1a-R613X_B6-830129.04.09.01',
       'Scn1a-R613X_B6-830129.04.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.04',
       'QN25.26.017.15m.06.01.01', 'QN25.26.017.15m.06.01.02',
       'QN25.26.017.15m.06.01.03', 'QN26.26.003.15.10.01',
       'QN26.26.003.15.10.03', 'C57BL6J-837955.14.13.01',
       'H25.51.018.11.54.01', 'H25.51.018.11.54.02',
       'H25.51.018.11.54.03', 'H25.51.018.11.54.04',
       'H25.51.018.11.54.05', 'H25.51.018.11.54.06',
       'H25.51.018.11.54.07', 'QN26.26.003.15.06.01',
       'H26.51.001.11.03.01', 'H26.51.001.11.03.02',
       'H26.51.001.11.03.03', 'H26.51.001.11.03.04',
       'C57BL6J-837954.04.09.01', 'Drd1a-Cre;Oi9-820240.06.11.01',
       'Drd1a-Cre;Oi9-820240.06.11.02', 'Drd1a-Cre;Oi9-820240.06.11.03',
       'QF25.26.019.15m.05.01', 'QF25.26.019.15m.05.02',
       'QF25.26.019.15m.05.04', 'QN25.26.018.15m.10.01.02',
       'QN25.26.018.15m.10.01.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827267.11.13.02',
       'QN25.26.018.15m.11.01.01', 'QN25.26.018.15m.11.01.02',
       'QN25.26.018.15m.11.01.03', 'QN25.26.018.15m.11.01.04',
       'QN25.26.018.15m.11.01.05', 'H25.51.018.11.02.01',
       'H25.51.018.11.02.02', 'H25.51.018.11.02.04',
       'H25.51.018.11.02.05', 'Scn1a-R613X_B6-830129.06.09.01',
       'Scn1a-R613X_B6-830129.06.09.04',
       'Gad2-IRES-Cre;Ai14-841410.16.03.01', 'QF25.26.019.15m.04.01',
       'QF25.26.019.15m.04.03', 'QF25.26.022.15m.05.01',
       'QF25.26.022.15m.05.02', 'QF25.26.022.15m.05.03',
       'QF25.26.022.15m.05.04', 'QN26.26.002.16.02B.02',
       'Gad2-IRES-Cre;Ai14-841407.14.03.01',
       'Gad2-IRES-Cre;Ai14-841407.14.03.02',
       'Gad2-IRES-Cre;Ai14-841407.14.03.03',
       'Gad2-IRES-Cre;Ai14-841407.14.03.04',
       'Gad2-IRES-Cre;Ai14-841407.14.03.05', 'QF25.26.028.14d.01.02',
       'QF25.26.028.14d.01.03', 'QF25.26.028.14d.01.04',
       'QN25.26.020.15m.04.03', 'C57BL6J-837955.04.13.01',
       'QF25.26.021.15m.06.01', 'QF25.26.021.15m.06.02',
       'QF25.26.021.15m.06.03', 'QF25.26.023.15m.06.03',
       'QF25.26.023.15m.06.04', 'H26.51.001.11.54.01',
       'H26.51.001.11.54.02', 'H26.51.001.11.54.03',
       'H26.51.001.11.54.05', 'H26.51.001.11.54.07',
       'H26.51.001.11.54.08', 'H26.51.001.11.54.09',
       'Gad2-IRES-Cre;Ai14-841408.13.13.01',
       'Gad2-IRES-Cre;Ai14-841408.13.13.02',
       'Vip-IRES-Cre-835274.14.03.01', 'Vip-IRES-Cre-835274.14.03.02',
       'Vip-IRES-Cre-835274.14.03.03',
       'Gad2-IRES-Cre;Ai14-841409.05.01.01',
       'Gad2-IRES-Cre;Ai14-841409.05.01.02', 'QN25.26.017.15m.05.01.01',
       'QN25.26.017.15m.05.01.03', 'QN25.26.017.15m.05.01.04',
       'QN25.26.017.15m.05.01.05', 'QN25.26.017.15m.05.01.06',
       'QN25.26.026.16.10.01', 'QN25.26.026.16.10.02',
       'QN25.26.026.16.10.03', 'QN25.26.026.16.10.04',
       'H25.51.016.11.55.02', 'H25.51.016.11.55.03',
       'H25.51.016.11.55.05', 'QF25.26.023.15m.13.03',
       'H25.51.017.11.52.01', 'H25.51.017.11.52.02',
       'QF25.26.016.15m.13.01.01', 'QF25.26.016.15m.13.01.02',
       'Pvalb-IRES-Cre;Ai14-830325.10.03.01',
       'Pvalb-IRES-Cre;Ai14-830325.10.03.02',
       'Pvalb-IRES-Cre;Ai14-830325.10.03.03',
       'Sst-IRES-Cre;Ai14-833443.12.13.01',
       'Sst-IRES-Cre;Ai14-833443.12.13.02',
       'Drd1a-Cre;Oi9-820240.05.11.02', 'C57BL6J-837955.11.13.01',
       'QF25.26.024.14d.02.01', 'QF25.26.024.14d.02.02',
       'QF25.26.028.14v.08.01', 'QF25.26.028.14v.08.02',
       'H25.51.015.11.54.01.01', 'H25.51.015.11.54.01.04',
       'QN26.26.002.15.05.01', 'QN26.26.002.15.05.02',
       'QN26.26.002.15.05.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.07.13.01',
       'H25.51.016.11.04.01', 'H25.51.016.11.04.02',
       'H25.51.016.11.04.03', 'H25.51.016.11.04.04',
       'H25.51.016.11.04.05', 'H25.51.016.11.04.06',
       'Gad2-IRES-Cre;Ai14-841406.04.09.01',
       'Gad2-IRES-Cre;Ai14-841406.04.09.02',
       'Drd1a-Cre;Oi9-813175.07.10.01', 'Drd1a-Cre;Oi9-813175.07.10.03',
       'Drd1a-Cre;Oi9-813175.08.10.02', 'Drd1a-Cre;Oi9-813175.08.10.03',
       'QF25.26.016.15m.09.01.01', 'QF25.26.016.15m.09.01.02',
       'QF25.26.016.15m.09.01.03', 'QN26.26.004.15.06.01',
       'QN26.26.004.15.06.02', 'QN26.26.004.15.06.03',
       'QN26.26.002.15.11.03', 'C57BL6J-823514.09.13.01',
       'C57BL6J-823514.09.13.02', 'C57BL6J-823514.09.13.03',
       'C57BL6J-837954.01.09.01', 'C57BL6J-837954.01.09.02',
       'QF25.26.019.15m.02.01', 'QF25.26.019.15m.02.02',
       'QF25.26.019.15m.02.03', 'QF25.26.019.15m.02.04',
       'QF25.26.019.15m.02.05', 'QF25.26.021.15m.05.01',
       'QF25.26.021.15m.05.02', 'QF25.26.021.15m.05.04',
       'Scn1a-R613X_B6-830133.06.01.02', 'C57BL6J-815107.05.04.02',
       'QN26.26.004.15.04.01', 'QN26.26.004.15.04.02',
       'QN26.26.004.15.04.03', 'H25.51.018.11.51.01',
       'H25.51.018.11.51.02', 'H25.51.018.11.51.03',
       'H25.51.018.11.51.04', 'H25.51.018.11.51.05',
       'H25.51.018.11.51.06', 'H25.51.018.11.51.07',
       'QF25.26.028.14v.10.02', 'QF25.26.028.14v.10.03',
       'QF25.26.028.14v.10.04', 'QF25.26.028.14v.10.05',
       'Sst-IRES-Cre;Ai14-833440.10.14.03', 'C57BL6J-823516.02.09.01',
       'C57BL6J-823516.02.09.03', 'QF25.26.028.14d.04.01',
       'QF25.26.028.14d.04.02', 'C57BL6J-823513.09.13.01',
       'C57BL6J-823513.09.13.02', 'C57BL6J-823513.09.13.03',
       'H26.51.001.11.52.01', 'H26.51.001.11.52.02',
       'H26.51.001.11.52.03', 'H26.51.001.11.52.04',
       'H26.51.001.11.52.05', 'H26.51.001.11.52.06',
       'Pvalb-IRES-Cre;Ai14-830327.06.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.06.09.02',
       'Pvalb-IRES-Cre;Ai14-830327.06.09.03', 'QF25.26.024.14v.01.01',
       'QF25.26.024.14v.01.03', 'QF25.26.024.14v.01.04',
       'C57BL6J-823513.12.13.01', 'C57BL6J-823515.04.09.03',
       'C57BL6J-823515.04.09.05', 'C57BL6J-823515.04.09.06',
       'Drd1a-Cre;Oi9-813175.05.10.01', 'Drd1a-Cre;Oi9-813175.05.10.02',
       'QF25.26.019.15m.01.01', 'QF25.26.019.15m.01.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827265.11.13.01',
       'C57BL6J-837954.06.09.01', 'H25.51.017.11.56.02',
       'H25.51.017.11.56.03', 'H25.51.016.11.05.01',
       'H25.51.016.11.05.02', 'H25.51.016.11.05.03',
       'H25.51.016.11.05.04', 'H25.51.016.11.05.05',
       'H25.51.016.11.05.06', 'H25.51.016.11.05.07',
       'H25.51.016.11.05.08', 'Gad2-IRES-Cre;Ai14-841410.16.04.02',
       'Gad2-IRES-Cre;Ai14-841410.16.04.03',
       'Gad2-IRES-Cre;Ai14-841410.16.04.04', 'C57BL6J-823514.12.13.01',
       'C57BL6J-823514.12.13.02', 'C57BL6J-823514.12.13.03',
       'C57BL6J-823514.12.13.04', 'Sst-IRES-Cre;Ai14-833439.07.13.01',
       'C57BL6J-823514.11.13.01', 'C57BL6J-823514.11.13.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.13.13.02',
       'C57BL6J-837957.04.09.01', 'C57BL6J-837957.04.09.02',
       'H25.51.016.11.54.01', 'H25.51.016.11.54.02',
       'H25.51.016.11.54.03', 'H25.51.016.11.54.04',
       'H25.51.016.11.54.05', 'QN26.26.002.15.03.02',
       'Scn1a-R613X_B6-830133.04.01.01', 'Scn1a-R613X_B6-830133.04.01.03',
       'Sst-IRES-Cre;Ai14-833440.12.13.01',
       'Sst-IRES-Cre;Ai14-833440.12.13.02',
       'Sst-IRES-Cre;Ai14-833440.12.13.03',
       'Pvalb-IRES-Cre;Ai14-830327.04.09.01',
       'Pvalb-IRES-Cre;Ai14-830327.04.09.04',
       'Pvalb-IRES-Cre;Ai14-830327.04.09.05',
       'Gad2-IRES-Cre;Ai14-841406.03.09.01',
       'Gad2-IRES-Cre;Ai14-841406.03.09.02',
       'Gad2-IRES-Cre;Ai14-841406.03.09.03',
       'Drd1a-Cre;Oi9-820240.04.11.03', 'C57BL6J-823513.07.13.01',
       'Sst-IRES-Cre;Ai14-833442.04.09.01',
       'Sst-IRES-Cre;Ai14-833442.04.09.02',
       'Sst-IRES-Cre;Ai14-833442.04.09.03',
       'Sst-IRES-Cre;Ai14-833444.13.14.01', 'QN25.26.026.16.12.01',
       'QN25.26.026.16.12.02', 'QN25.26.026.16.12.03',
       'QN25.26.026.16.12.04', 'QF25.26.023.15m.07.01',
       'QF25.26.023.15m.07.03', 'QF25.26.023.15m.07.05',
       'QF25.26.023.15m.07.06', 'QF25.26.023.15m.07.07',
       'C57BL6J-839148.05.09.01', 'C57BL6J-839148.05.09.02',
       'C57BL6J-839148.05.09.03', 'C57BL6J-839148.05.09.04',
       'Gad2-IRES-Cre;Ai14-841407.14.04.01',
       'Gad2-IRES-Cre;Ai14-841407.14.04.02', 'C57BL6J-837957.03.09.01',
       'C57BL6J-837954.07.09.01', 'C57BL6J-837954.07.09.02',
       'QN25.26.029.15.07.02', 'Sst-IRES-Cre;Ai14-833439.11.13.01',
       'Sst-IRES-Cre;Ai14-833439.11.13.02',
       'Sst-IRES-Cre;Ai14-833439.11.13.03',
       'Vip-IRES-Cre-835276.17.04.01', 'Vip-IRES-Cre-835276.17.04.02',
       'Vip-IRES-Cre-835276.17.04.03', 'Vip-IRES-Cre-835276.17.04.04',
       'Pvalb-IRES-Cre;Ai14-830327.03.09.02',
       'Pvalb-IRES-Cre;Ai14-830327.03.09.03',
       'Pvalb-IRES-Cre;Ai14-830327.03.09.05', 'QN26.26.003.15.08.02',
       'QF25.26.023.15m.04.02', 'QF25.26.023.15m.04.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.15.13.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.15.13.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.15.13.03',
       'C57BL6J-815107.06.03.01', 'C57BL6J-815107.06.03.03',
       'C57BL6J-815107.06.03.05', 'C57BL6J-815107.06.03.06',
       'Sst-IRES-Cre;Ai14-833444.16.13.01',
       'Sst-IRES-Cre;Ai14-833443.11.13.01',
       'Sst-IRES-Cre;Ai14-833443.11.13.02', 'QF25.26.016.15m.06.01.01',
       'QF25.26.016.15m.06.01.02', 'QF25.26.016.15m.06.01.03',
       'H25.51.016.11.06.01', 'H25.51.016.11.06.02',
       'H25.51.016.11.06.03', 'H25.51.016.11.06.04',
       'QF25.26.028.14d.03.01', 'QF25.26.028.14d.03.02',
       'QF25.26.028.14d.03.03', 'Vip-IRES-Cre-835276.15.04.01',
       'Vip-IRES-Cre-835276.15.04.02', 'Drd1a-Cre;Oi9-820240.06.10.01',
       'Scn1a-R613X_B6-830133.03.01.01', 'Scn1a-R613X_B6-830133.03.01.02',
       'H25.51.017.11.57.01', 'H25.51.017.11.57.02',
       'H25.51.017.11.57.04', 'H25.51.017.11.57.05',
       'H25.51.017.11.57.06', 'H25.51.017.11.57.07',
       'H25.51.017.11.57.08', 'H25.51.017.11.57.09',
       'H25.51.017.11.57.10', 'H25.51.017.11.57.11',
       'QN26.26.002.16.02A.02', 'QN26.26.002.16.02A.03',
       'QN26.26.002.16.02A.04', 'QN26.26.002.16.02A.05',
       'QN25.26.018.15m.09.01.01', 'QN25.26.018.15m.09.01.03',
       'QN26.26.003.15.15.01', 'QN26.26.003.15.15.02',
       'QN26.26.003.15.15.03', 'QN26.26.003.15.15.04',
       'QN26.26.003.15.15.05', 'QF25.26.016.15m.11.01.01',
       'H25.51.016.11.07.01', 'H25.51.016.11.07.02',
       'H25.51.016.11.07.03', 'H25.51.016.11.07.04',
       'H25.51.016.11.07.05', 'H25.51.016.11.07.06',
       'H25.51.016.11.07.07', 'QN25.26.020.15m.01.01',
       'Gad2-IRES-Cre;Ai14-841407.13.03.01',
       'Gad2-IRES-Cre;Ai14-841407.13.03.02',
       'Gad2-IRES-Cre;Ai14-841407.13.03.03',
       'Vip-IRES-Cre-835276.16.03.01', 'Vip-IRES-Cre-835276.16.03.02',
       'Drd1a-Cre;Oi9-820239.06.10.01', 'Drd1a-Cre;Oi9-820239.06.10.02',
       'Drd1a-Cre;Oi9-820239.06.10.03', 'Drd1a-Cre;Oi9-820239.06.10.04',
       'Drd1a-Cre;Oi9-820239.06.10.05', 'QN26.26.002.15.10.01',
       'QN26.26.002.15.10.02', 'QN26.26.002.15.10.03',
       'QN26.26.002.15.10.04', 'QN26.26.002.15.10.05',
       'Vip-IRES-Cre-835274.11.03.01', 'QN25.26.026.16.13.01',
       'QN25.26.026.16.13.02', 'QN25.26.026.16.13.03',
       'QN25.26.026.16.13.04', 'QN25.26.026.16.13.05',
       'QN25.26.029.15.12.01', 'QN25.26.029.15.12.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827263.06.14.01',
       'Vip-IRES-Cre-835274.15.03.01', 'Vip-IRES-Cre-835274.15.03.02',
       'Vip-IRES-Cre-835274.15.03.03',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.01',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.02',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.03',
       'Pvalb-IRES-Cre;Ai14-830326.13.03.05',
       'Sst-IRES-Cre;Ai14-833439.10.14.01',
       'Sst-IRES-Cre;Ai14-833441.14.14.02', 'QN25.26.029.15.14.02',
       'QN25.26.029.15.14.03', 'Vip-IRES-Cre-835276.15.03.01',
       'H25.51.016.11.52.03', 'H25.51.016.11.52.05',
       'QN25.26.018.15m.04.01.01', 'QN25.26.018.15m.04.01.02',
       'Scn1a-R613X_B6-830133.05.01.02', 'Scn1a-R613X_B6-830133.05.01.03',
       'Scn1a-R613X_B6-830133.05.01.04', 'QF25.26.019.15m.12.01',
       'QF25.26.019.15m.12.02', 'QF25.26.019.15m.12.03',
       'QF25.26.019.15m.12.04', 'QF25.26.019.15m.12.05',
       'QF25.26.019.15m.12.06', 'QF25.26.019.15m.12.07',
       'C57BL6J-839149.02.09.01', 'C57BL6J-839149.02.09.02',
       'C57BL6J-839149.02.09.03', 'C57BL6J-839149.02.09.04',
       'C57BL6J-823513.10.13.01', 'QF25.26.024.14v.04.02',
       'QF25.26.024.14v.04.03', 'Pvalb-IRES-Cre;Ai14-830325.09.03.01',
       'Pvalb-IRES-Cre;Ai14-830325.09.03.02',
       'Pvalb-IRES-Cre;Ai14-830325.09.03.03',
       'Pvalb-IRES-Cre;Ai14-830325.09.03.04',
       'Gad2-IRES-Cre;Ai14-841409.03.02.01', 'QF25.26.019.15m.11.01',
       'QF25.26.019.15m.11.02', 'QF25.26.019.15m.11.03',
       'QF25.26.019.15m.11.04', 'QF25.26.019.15m.11.05',
       'H25.51.017.11.54.01', 'C57BL6J-839148.04.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.08.13.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.08.13.02',
       'Sst-IRES-Cre;Ai14-822449.06.12.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.05.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.05.09.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.05.09.04',
       'C57BL6J-837955.10.13.01', 'QN25.26.017.15m.04.01.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-827264.14.13.04',
       'H26.51.001.11.51.01', 'H26.51.001.11.51.02',
       'H26.51.001.11.51.04', 'H26.51.001.11.51.05',
       'Gad2-IRES-Cre;Ai14-841406.02.09.01',
       'Gad2-IRES-Cre;Ai14-841406.02.09.02',
       'Gad2-IRES-Cre;Ai14-841406.02.09.03', 'QF25.26.023.15m.09.02',
       'Scn1a-R613X_B6-830129.03.09.01', 'H26.06.351.11.04.01',
       'H25.51.017.11.51.01', 'H25.51.017.11.51.02',
       'H25.51.017.11.51.03', 'H25.51.017.11.51.04',
       'H25.51.017.11.51.05', 'H25.51.017.11.51.06',
       'QF25.26.024.15m.07.01', 'QF25.26.024.15m.07.05',
       'QF25.26.021.15m.10.01', 'H25.51.015.11.55.01.01',
       'H25.51.015.11.55.01.02', 'H25.51.015.11.55.01.04',
       'C57BL6J-837957.05.09.01', 'C57BL6J-837957.05.09.03',
       'Gad2-IRES-Cre;Ai14-841410.17.04.01', 'C57BL6J-823514.14.13.01',
       'H25.51.018.11.52.01', 'H25.51.018.11.52.02',
       'H25.51.018.11.52.03', 'H25.51.018.11.52.04',
       'H25.51.018.11.52.05', 'H25.51.018.11.52.06',
       'H25.51.018.11.52.07', 'Drd1a-Cre;Oi9-820240.05.10.01',
       'QN25.26.017.15m.07.01.02', 'QF25.26.019.16.02A.01',
       'QN26.26.003.15.09.01', 'QN26.26.003.15.09.02',
       'QN26.26.003.15.09.04', 'QN26.26.003.15.09.05',
       'Gad2-IRES-Cre;Ai14-841410.17.03.02',
       'Gad2-IRES-Cre;Ai14-841410.17.03.03', 'C57BL6J-815107.04.04.01',
       'C57BL6J-815107.04.04.02', 'C57BL6J-815107.04.04.03',
       'C57BL6J-815107.04.04.04', 'Gad2-IRES-Cre;Ai14-841408.12.13.01',
       'Gad2-IRES-Cre;Ai14-841408.12.13.02',
       'Gad2-IRES-Cre;Ai14-841408.12.13.03',
       'Gad2-IRES-Cre;Ai14-841408.12.13.04', 'QN26.26.002.15.12.01',
       'QN26.26.002.15.12.02', 'QN26.26.002.15.12.03',
       'H25.51.017.11.53.01', 'H25.51.017.11.53.02',
       'Drd1a-Cre;Oi9-813175.06.10.01', 'Drd1a-Cre;Oi9-813175.06.10.02',
       'Drd1a-Cre;Oi9-813175.06.10.03', 'Drd1a-Cre;Oi9-813175.06.10.04',
       'QF25.26.022.15m.06.01', 'QF25.26.022.15m.06.02',
       'Sst-IRES-Cre;Ai14-833443.07.14.01',
       'Sst-IRES-Cre;Ai14-833443.07.14.02',
       'Sst-IRES-Cre;Ai14-833443.07.14.03', 'QF25.26.022.15m.13.02',
       'Gad2-IRES-Cre;Ai14-841407.12.03.02',
       'Gad2-IRES-Cre;Ai14-841407.12.04.01',
       'Gad2-IRES-Cre;Ai14-841407.12.04.03', 'C57BL6J-837954.05.09.01',
       'C57BL6J-837954.05.09.02', 'QN26.26.003.15.07.01',
       'H25.51.018.11.01.01', 'H25.51.018.11.01.02',
       'H25.51.018.11.01.03', 'H25.51.018.11.01.04',
       'Drd1a-Cre;Oi9-820239.07.10.03', 'Drd1a-Cre;Oi9-820239.07.10.04',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.04.09.01',
       'H26.51.001.11.04.01', 'H26.51.001.11.04.02',
       'H26.51.001.11.04.03', 'H26.51.001.11.05.01',
       'H26.51.001.11.05.02', 'H25.51.016.11.51.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.01',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.02',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.03',
       'Slc17a8-IRES2-Cre-neo;Ai14-834538.02.09.05',
       'C57BL6J-823513.09.14.01', 'C57BL6J-815107.06.04.03',
       'C57BL6J-815107.06.04.04', 'H25.51.017.11.59.01',
       'QF25.26.024.14d.01.01', 'C57BL6J-837955.12.13.01',
       'QF25.26.024.15m.01.01', 'H25.51.017.11.62.01',
       'H25.51.017.11.62.03', 'H25.51.017.11.62.04',
       'H25.51.017.11.62.05', 'H25.51.017.11.62.06'], dtype=object)

In [25]:
[f for f in jem_lims_tube_df['jem-id_cell_specimen'] if f.startswith('H26.51.001.11.04')]

['H26.51.001.11.04.01', 'H26.51.001.11.04.02', 'H26.51.001.11.04.03']

In [34]:
group='ivscc'
data_variables = load_data_variables()

jem_lims_name_df["test-jem_lims"] = np.where((jem_lims_name_df["jem-id_cell_specimen"] == jem_lims_name_df["lims-id_cell_specimen"])&(jem_lims_name_df["jem-id_patched_cell_container"] == jem_lims_name_df["lims-id_patched_cell_container"]), "Both",
                                np.where((jem_lims_name_df["jem-id_cell_specimen"].isnull()), "LIMS",
                                np.where((jem_lims_name_df["lims-id_cell_specimen"].isnull()), "JEM",
                                np.where((jem_lims_name_df["jem-id_patched_cell_container"] != jem_lims_name_df["lims-id_patched_cell_container"]), "Mismatched Patch Tube", "Unsure"))))
# Create a new column (test-jem_lims) for jem_lims_tube_df
jem_lims_tube_df["test-jem_lims"] = np.where((jem_lims_tube_df["jem-id_cell_specimen"] == jem_lims_tube_df["lims-id_cell_specimen"])&(jem_lims_tube_df["jem-id_patched_cell_container"] == jem_lims_tube_df["lims-id_patched_cell_container"]), "Both",
                                np.where((jem_lims_tube_df["jem-id_cell_specimen"].isnull()), "LIMS",
                                np.where((jem_lims_tube_df["lims-id_cell_specimen"].isnull()), "JEM",
                                np.where((jem_lims_tube_df["jem-id_cell_specimen"] != jem_lims_tube_df["lims-id_cell_specimen"]), "Mismatched Specimen ID", "Unsure"))))
# Create a new column (test-pc_tubes)
jem_lims_name_df["test-pc_tubes"] = np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("c")) & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PCS4")) & (jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PCS4")), "Correct - Culture JEM/LIMS Tube",
                                np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("c")) & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PCS4", na=False)) & (~jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PCS4", na=False)), "Incorrect - Culture JEM/LIMS Tube",
                                np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("c")) & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PCS4", na=False)) & (jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PCS4", na=False)), "Incorrect - Culture JEM Tube",
                                np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("c")) & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PCS4", na=False)) & (~jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PCS4", na=False)), "Incorrect - Culture LIMS Tube", "Not Applicable"))))

# Create a new column (test-px_tubes)
jem_lims_name_df["test-px_tubes"] = np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("x")) & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4")) & (jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PXS4")), "Correct - Experimental JEM/LIMS Tube",
                                np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("x")) & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)) & (~jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - Experimental JEM/LIMS Tube",
                                np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("x")) & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)) & (jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect -Experimental JEM Tube",
                                np.where((jem_lims_name_df["lims-id_project_code"].str.endswith("x")) & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)) & (~jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - Experimental LIMS Tube", "Not Applicable"))))

# Create a new column (test-jem_projects)
jem_lims_name_df["test-jem_projects"] = np.where((jem_lims_name_df["jem-project_name"] == "1% Biocytin Pilot") & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Correct - 1% Biocytin",
                                    np.where((jem_lims_name_df["jem-project_name"] == "1% Biocytin Pilot") & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - 1% Biocytin",  
                                    np.where((jem_lims_name_df["jem-project_name"] == "Extended PBS Morphology Pilot") & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Correct - Extended PBS Morphology",
                                    np.where((jem_lims_name_df["jem-project_name"] == "Extended PBS Morphology Pilot") & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - Extended PBS Morphology",
                                    np.where((jem_lims_name_df["jem-project_name"] == "1% Biocytin + Extended PBS Morphology Pilot") & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Correct - 1% Biocytin + Extended PBS Morphology",
                                    np.where((jem_lims_name_df["jem-project_name"] == "1% Biocytin + Extended PBS Morphology Pilot") & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - 1% Biocytin + Extended PBS Morphology",  
                                    np.where((jem_lims_name_df["jem-project_name"] == "Morphology Clearing") & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Correct - Morphology Clearing",
                                    np.where((jem_lims_name_df["jem-project_name"] == "Morphology Clearing") & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - Morphology Clearing",
                                    np.where((jem_lims_name_df["jem-project_name"] == "Picrotoxin Validation") & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Correct - Picrotoxin Validation",
                                    np.where((jem_lims_name_df["jem-project_name"] == "Picrotoxin Validation") & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - Picrotoxin Validation",
                                    np.where((jem_lims_name_df["jem-project_name"] == "None") & (~jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Correct - No Project",
                                    np.where((jem_lims_name_df["jem-project_name"] == "None") & (jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PXS4", na=False)), "Incorrect - No Project", "Not Applicable"))))))))))))

# Create a new column (test-lims_structure) for lims_df
lims_df["test-lims_structure"] = np.where((lims_df["lims-structure"].isnull()), "Correct",
                                np.where((~lims_df["lims-structure"].isnull()), "Incorrect", "Not Applicable"))

if (len(jem_df) > 0) & (len(lims_df) > 0):
# Adding new column with project codes
    if group == "ivscc":
        jem_lims_name_df["project_code"] = np.where((jem_lims_name_df["jem-slice_level_project"] == "PGA"), data_variables["project_dictionary"]["PGA"],
                                            np.where((jem_lims_name_df["jem-slice_level_project"] == "HMBA-UM1"), data_variables["project_dictionary"]["HMBA"],
                                            np.where((jem_lims_name_df["jem-slice_level_project"] == "Mouse Connects-UM1"), data_variables["project_dictionary"]["mouse_connects"],
                                            np.where((jem_lims_name_df["jem-slice_level_project"] == "LC/DR - R01"), data_variables["project_dictionary"]["lc_dr"],
                                            np.where((jem_lims_name_df["jem-slice_level_project"] == "D1R KO Pilot"), data_variables["project_dictionary"]["PGA"],
                                            np.where((jem_lims_name_df["jem-slice_level_project"] == "PatchLink"), data_variables["project_dictionary"]["patchlink"],
                                            np.where((jem_lims_name_df["jem-slice_level_project"] == "Dravet"), data_variables["project_dictionary"]["dravet"],
                                            np.where((jem_lims_name_df["jem-slice_level_project"] == "Thalamus-U19"), data_variables["project_dictionary"]["roi_thalamus"], data_variables["project_dictionary"]["PGA"]))))))))
    if group == "hct":
        jem_lims_name_df["project_code"] = np.where((jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PYS4")) & (jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PYS4")), data_variables["project_dictionary"]["psilocybin"],
                                            np.where((jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("P7S4")) & (jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("P7S4")) & (jem_lims_name_df["lims-id_project_code"] == "MET-NM"), data_variables["project_dictionary"]["neuromodulation"],
                                            np.where((jem_lims_name_df["jem-id_patched_cell_container"].str.startswith("PCS4")) & (jem_lims_name_df["lims-id_patched_cell_container"].str.startswith("PCS4")) & (jem_lims_name_df["lims-id_project_code"] == "MET-NM"), data_variables["project_dictionary"]["neuromodulation"], data_variables["project_dictionary"]["PGA"])))

    # Create a date check for jem 
    jem_lims_name_df["jem-date_container"] = jem_lims_name_df["jem-id_patched_cell_container"].str[5:11]
    jem_lims_name_df["jem-date_container"] = pd.to_datetime(jem_lims_name_df["jem-date_container"], format='%y%m%d').dt.strftime("%m/%d/%Y")
    jem_lims_name_df["jem-date_check"] = jem_lims_name_df["jem-date_patch"] == jem_lims_name_df["jem-date_container"]
    # Use test_patch_date_df to check for mismatched dates and patched cell container dates
    test_patch_date_df = jem_lims_name_df[["jem-date_check", "jem-date_patch", "jem-id_cell_specimen", "jem-id_patched_cell_container", "lims-id_cell_specimen", "lims-id_patched_cell_container"]].copy()
    test_patch_date_df.dropna(subset=["jem-date_patch"], inplace=True)
    test_patch_date_df.sort_values(by="lims-id_patched_cell_container", inplace=True)

    # Create a test_df
    test_name_df = generate_test_df(jem_lims_name_df)
    test_tube_df = generate_test_df(jem_lims_tube_df)

    # Test dataframes
    test_patch_date_df = test_patch_date_df[test_patch_date_df["jem-date_check"] == False]
    test_jem_df = test_name_df[test_name_df["test-jem_lims"] == "JEM"]
    test_lims_df = test_name_df[test_name_df["test-jem_lims"] == "LIMS"]
    test_mismatch_specimen_df = test_tube_df[test_tube_df["test-jem_lims"] == "Mismatched Specimen ID"]
    test_mismatch_container_df = test_name_df[test_name_df["test-jem_lims"] == "Mismatched Patch Tube"]
    test_pc_df = jem_lims_name_df[jem_lims_name_df["test-pc_tubes"].str.startswith("Incorrect")]
    test_px_df = jem_lims_name_df[jem_lims_name_df["test-px_tubes"].str.startswith("Incorrect")]
    test_lims_structure_df = lims_df[lims_df["test-lims_structure"] == "Incorrect"]
    test_jem_projects_df = jem_lims_name_df[jem_lims_name_df["test-jem_projects"].str.startswith("Incorrect")]

    if (len(test_patch_date_df) > 0) or (len(test_jem_df) > 0) or (len(test_lims_df) > 0) or (len(test_mismatch_specimen_df) > 0) or (len(test_mismatch_container_df) > 0) or (len(test_pc_df) > 0) or (len(test_px_df) > 0) or (len(test_lims_structure_df) > 0) or (len(test_jem_projects_df) > 0):
        # Tests for mismatched jem patch date and jem patch tube date
        test_mismatch_patch_date(test_patch_date_df)
        # Tests for missing LIMS information
        test_miss_lims(test_jem_df, test_mismatch_specimen_df, test_mismatch_container_df)
        # Tests for missing JEM information
        test_miss_jem(test_lims_df, test_mismatch_specimen_df, test_mismatch_container_df)
        # Tests for mismatched jem/lims specimen id information
        test_mismatch_specimen(test_mismatch_specimen_df)
        # Tests for mismatched jem/lims patch tube information
        test_mismatch_patch_tube(test_mismatch_container_df)
        # Tests for pc tubes
        test_pc_tubes(test_pc_df)
        # Tests for px tubes
        test_px_tubes(test_px_df)
        # Tests for blank structure field in LIMS for Non-Human Primate specimens
        test_lims_structure(test_lims_structure_df)
        # Tests for jem projects
        test_jem_projects(test_jem_projects_df)

#-----Mismatched JEM Patch Date & JEM Patch Tube Date-----#
Description: In the JEM form, please correct the JEM Patch Date and Patch Tube!

1) JEM Specimen ID: H26.51.001.11.04.01
   - JEM Patch Date: 01/13/2026
   - JEM Patch Tube: P8S4_260114_356_A01
2) JEM Specimen ID: H26.51.001.11.04.02
   - JEM Patch Date: 01/13/2026
   - JEM Patch Tube: P8S4_260114_357_A01
3) JEM Specimen ID: H26.51.001.11.04.03
   - JEM Patch Date: 01/13/2026
   - JEM Patch Tube: P8S4_260114_358_A01

#-----Missing LIMS Information-----#
Description: Please use the JEM Specimen ID and JEM Patch Tube to update LIMS!

1) JEM Specimen ID: C57BL6J-839149.04.09.01
   - JEM Patch Tube: P6S4_251217_401_A01
2) JEM Specimen ID: C57BL6J-839149.04.09.02
   - JEM Patch Tube: P6S4_251217_402_A01
3) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830327.02.09.01
   - JEM Patch Tube: P6S4_251114_401_A01
4) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830327.02.09.03
   - JEM Patch Tube: P6S4_251114_402_A01
5) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830327.02.09.04
   - JEM Patch Tube: P6S4_251114_403_A01
6) JEM Specimen ID: QN25.26.029.15.11.03
   - JEM Patch Tube: PCS4_251215_402_A01
7) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-828949.14.03.02
   - JEM Patch Tube: PVS4_251104_451_A01
8) JEM Specimen ID: Sst-IRES-Cre;Ai14-833441.07.13.01
   - JEM Patch Tube: P9S4_251120_551_A01
9) JEM Specimen ID: C57BL6J-837955.09.14.01
   - JEM Patch Tube: P8S4_251209_353_A01
10) JEM Specimen ID: QF25.26.019.15m.03.01
   - JEM Patch Tube: PCS4_251015_551_A01
11) JEM Specimen ID: QF25.26.019.15m.03.02
   - JEM Patch Tube: PCS4_251015_552_A01
12) JEM Specimen ID: QF25.26.019.15m.03.03
   - JEM Patch Tube: PCS4_251015_553_A01
13) JEM Specimen ID: QF25.26.019.15m.03.04
   - JEM Patch Tube: PCS4_251015_554_A01
14) JEM Specimen ID: H25.51.018.11.03.01
   - JEM Patch Tube: P4S4_251218_153_A01
15) JEM Specimen ID: H25.51.018.11.03.02
   - JEM Patch Tube: P4S4_251218_154_A01
16) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830325.11.04.01
   - JEM Patch Tube: P9S4_251106_551_A01
17) JEM Specimen ID: C57BL6J-837954.08.09.01
   - JEM Patch Tube: P6S4_251210_403_A01
18) JEM Specimen ID: C57BL6J-837954.08.09.02
   - JEM Patch Tube: P6S4_251210_404_A01
19) JEM Specimen ID: C57BL6J-839151.03.09.01
   - JEM Patch Tube: P4S4_251218_151_A01
20) JEM Specimen ID: C57BL6J-839151.03.09.02
   - JEM Patch Tube: P4S4_251218_152_A01
21) JEM Specimen ID: QN26.26.002.15.02.01
   - JEM Patch Tube: P9S4_260113_551_A01
22) JEM Specimen ID: QN26.26.002.15.02.03
   - JEM Patch Tube: P9S4_260113_552_A01
23) JEM Specimen ID: QN26.26.002.15.02.04
   - JEM Patch Tube: P9S4_260113_553_A01
24) JEM Specimen ID: QN25.26.026.16.06.01
   - JEM Patch Tube: PCS4_251126_401_A01
25) JEM Specimen ID: QN25.26.026.16.06.02
   - JEM Patch Tube: PCS4_251126_402_A01
26) JEM Specimen ID: QN25.26.026.16.06.03
   - JEM Patch Tube: PCS4_251126_403_A01
27) JEM Specimen ID: QN25.26.026.16.06.05
   - JEM Patch Tube: PCS4_251126_404_A01
28) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830327.05.09.01
   - JEM Patch Tube: PVS4_251114_451_A01
29) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830327.05.09.02
   - JEM Patch Tube: PVS4_251114_452_A01
30) JEM Specimen ID: H25.51.018.11.53.01
   - JEM Patch Tube: PCS4_251222_401_A01
31) JEM Specimen ID: H25.51.018.11.53.03
   - JEM Patch Tube: PCS4_251222_402_A01
32) JEM Specimen ID: H25.51.018.11.53.04
   - JEM Patch Tube: PCS4_251222_403_A01
33) JEM Specimen ID: H25.51.018.11.53.05
   - JEM Patch Tube: PCS4_251222_404_A01
34) JEM Specimen ID: H25.51.018.11.53.06
   - JEM Patch Tube: PCS4_251222_405_A01
35) JEM Specimen ID: H25.51.018.11.53.07
   - JEM Patch Tube: PCS4_251222_406_A01
36) JEM Specimen ID: C57BL6J-823514.08.13.02
   - JEM Patch Tube: P8S4_251002_351_A01
37) JEM Specimen ID: C57BL6J-823514.08.13.03
   - JEM Patch Tube: P8S4_251002_352_A01
38) JEM Specimen ID: QN26.26.003.15.17.01
   - JEM Patch Tube: PCS4_260116_351_A01
39) JEM Specimen ID: QN26.26.003.15.17.02
   - JEM Patch Tube: PCS4_260116_352_A01
40) JEM Specimen ID: QN26.26.003.15.17.03
   - JEM Patch Tube: PCS4_260116_353_A01
41) JEM Specimen ID: QN26.26.003.15.17.04
   - JEM Patch Tube: PCS4_260116_354_A01
42) JEM Specimen ID: QN26.26.003.15.17.05
   - JEM Patch Tube: PCS4_260116_355_A01
43) JEM Specimen ID: Sst-IRES-Cre;Ai14-822449.08.11.01
   - JEM Patch Tube: P8S4_251007_351_A01
44) JEM Specimen ID: Sst-IRES-Cre;Ai14-822449.08.11.02
   - JEM Patch Tube: P8S4_251007_352_A01
45) JEM Specimen ID: QF25.26.024.14v.05.01
   - JEM Patch Tube: PCS4_251121_151_A01
46) JEM Specimen ID: QF25.26.024.14v.05.02
   - JEM Patch Tube: PCS4_251121_152_A01
47) JEM Specimen ID: H25.51.016.11.53.01
   - JEM Patch Tube: PCS4_251028_551_A01
48) JEM Specimen ID: H25.51.016.11.53.04
   - JEM Patch Tube: PCS4_251028_552_A01
49) JEM Specimen ID: H25.51.016.11.53.05
   - JEM Patch Tube: PCS4_251028_553_A01
50) JEM Specimen ID: H25.51.016.11.53.07
   - JEM Patch Tube: PCS4_251028_554_A01
51) JEM Specimen ID: H25.51.016.11.53.08
   - JEM Patch Tube: PCS4_251028_555_A01
52) JEM Specimen ID: QF25.26.024.14v.02.01
   - JEM Patch Tube: PCS4_251119_151_A01
53) JEM Specimen ID: QF25.26.024.14v.02.02
   - JEM Patch Tube: PCS4_251119_152_A01
54) JEM Specimen ID: Sst-IRES-Cre;Ai14-822449.07.11.01
   - JEM Patch Tube: P8S4_251007_353_A01
55) JEM Specimen ID: Sst-IRES-Cre;Ai14-822449.07.11.02
   - JEM Patch Tube: P8S4_251007_354_A01
56) JEM Specimen ID: Sst-IRES-Cre;Ai14-833442.06.09.01
   - JEM Patch Tube: P6S4_251121_401_A01
57) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.01
   - JEM Patch Tube: P4S4_251014_151_A01
58) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.02
   - JEM Patch Tube: P4S4_251014_152_A01
59) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827263.09.14.03
   - JEM Patch Tube: P4S4_251014_153_A01
60) JEM Specimen ID: C57BL6J-837954.03.09.01
   - JEM Patch Tube: P8S4_251210_351_A01
61) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-828949.15.04.01
   - JEM Patch Tube: P8S4_251104_351_A01
62) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-828949.15.04.03
   - JEM Patch Tube: P8S4_251104_352_A01
63) JEM Specimen ID: Sst-IRES-Cre;Ai14-833444.10.13.01
   - JEM Patch Tube: P4S4_251204_151_A01
64) JEM Specimen ID: C57BL6J-839148.03.09.02
   - JEM Patch Tube: P8S4_251215_351_A01
65) JEM Specimen ID: C57BL6J-839148.03.09.03
   - JEM Patch Tube: P8S4_251215_352_A01
66) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841407.13.04.01
   - JEM Patch Tube: P9S4_260108_551_A01
67) JEM Specimen ID: Sst-IRES-Cre;Ai14-833444.09.13.01
   - JEM Patch Tube: PVS4_251204_451_A01
68) JEM Specimen ID: Vip-IRES-Cre-835274.13.03.01
   - JEM Patch Tube: P9S4_251205_552_A01
69) JEM Specimen ID: Sst-IRES-Cre;Ai14-833441.12.13.01
   - JEM Patch Tube: P8S4_251120_351_A01
70) JEM Specimen ID: Sst-IRES-Cre;Ai14-833441.12.13.02
   - JEM Patch Tube: P8S4_251120_352_A01
71) JEM Specimen ID: C57BL6J-837954.02.09.01
   - JEM Patch Tube: P4S4_251210_151_A01
72) JEM Specimen ID: C57BL6J-837954.02.09.02
   - JEM Patch Tube: P4S4_251210_152_A01
73) JEM Specimen ID: C57BL6J-837954.02.09.03
   - JEM Patch Tube: P4S4_251210_153_A01
74) JEM Specimen ID: C57BL6J-837954.02.09.04
   - JEM Patch Tube: P4S4_251210_154_A01
75) JEM Specimen ID: C57BL6J-837954.02.09.05
   - JEM Patch Tube: P4S4_251210_155_A01
76) JEM Specimen ID: QF25.26.023.15m.14.01
   - JEM Patch Tube: PCS4_251112_151_A01
77) JEM Specimen ID: QF25.26.023.15m.14.02
   - JEM Patch Tube: PCS4_251112_152_A01
78) JEM Specimen ID: QF25.26.023.15m.14.03
   - JEM Patch Tube: PCS4_251112_153_A01
79) JEM Specimen ID: QF25.26.023.15m.14.05
   - JEM Patch Tube: PCS4_251112_154_A01
80) JEM Specimen ID: QF25.26.024.14v.03.01
   - JEM Patch Tube: PCS4_251121_351_A01
81) JEM Specimen ID: QF25.26.024.14v.03.02
   - JEM Patch Tube: PCS4_251121_352_A01
82) JEM Specimen ID: QF25.26.024.14v.03.03
   - JEM Patch Tube: PCS4_251121_353_A01
83) JEM Specimen ID: C57BL6J-839151.04.09.01
   - JEM Patch Tube: P6S4_251218_401_A01
84) JEM Specimen ID: Drd1a-Cre;Oi9-820240.04.10.01
   - JEM Patch Tube: PXS4_251216_352_A01
85) JEM Specimen ID: Drd1a-Cre;Oi9-820240.04.10.02
   - JEM Patch Tube: PXS4_251216_353_A01
86) JEM Specimen ID: QF25.26.023.15m.11.01
   - JEM Patch Tube: PCS4_251106_351_A01
87) JEM Specimen ID: QF25.26.023.15m.11.02
   - JEM Patch Tube: PCS4_251106_352_A01
88) JEM Specimen ID: Sst-IRES-Cre;Ai14-822449.11.11.01
   - JEM Patch Tube: P6S4_251007_401_A01
89) JEM Specimen ID: QF25.26.023.15m.12.01
   - JEM Patch Tube: PCS4_251107_351_A01
90) JEM Specimen ID: QF25.26.023.15m.12.02
   - JEM Patch Tube: PCS4_251107_352_A01
91) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.01
   - JEM Patch Tube: P9S4_251031_551_A01
92) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.02
   - JEM Patch Tube: P9S4_251031_552_A01
93) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827268.03.09.03
   - JEM Patch Tube: P9S4_251031_553_A01
94) JEM Specimen ID: C57BL6J-815107.05.03.01
   - JEM Patch Tube: P9S4_251009_551_A01
95) JEM Specimen ID: Scn1a-R613X_B6-830129.04.09.01
   - JEM Patch Tube: P6S4_251016_402_A01
96) JEM Specimen ID: Scn1a-R613X_B6-830129.04.09.02
   - JEM Patch Tube: P6S4_251016_403_A01
97) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.01
   - JEM Patch Tube: P6S4_251203_401_A01
98) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.03
   - JEM Patch Tube: P6S4_251203_402_A01
99) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-834538.01.09.04
   - JEM Patch Tube: P6S4_251203_403_A01
100) JEM Specimen ID: QN25.26.017.15m.06.01.01
   - JEM Patch Tube: P6S4_250924_402_A01
101) JEM Specimen ID: QN25.26.017.15m.06.01.02
   - JEM Patch Tube: P6S4_250924_403_A01
102) JEM Specimen ID: QN25.26.017.15m.06.01.03
   - JEM Patch Tube: P6S4_250924_404_A01
103) JEM Specimen ID: QN26.26.003.15.10.01
   - JEM Patch Tube: PCS4_260121_451_A01
104) JEM Specimen ID: QN26.26.003.15.10.03
   - JEM Patch Tube: PCS4_260121_452_A01
105) JEM Specimen ID: C57BL6J-837955.14.13.01
   - JEM Patch Tube: PVS4_251209_452_A01
106) JEM Specimen ID: H25.51.018.11.54.01
   - JEM Patch Tube: PCS4_251223_401_A01
107) JEM Specimen ID: H25.51.018.11.54.02
   - JEM Patch Tube: PCS4_251223_402_A01
108) JEM Specimen ID: H25.51.018.11.54.03
   - JEM Patch Tube: PCS4_251223_403_A01
109) JEM Specimen ID: H25.51.018.11.54.04
   - JEM Patch Tube: PCS4_251223_404_A01
110) JEM Specimen ID: H25.51.018.11.54.05
   - JEM Patch Tube: PCS4_251223_405_A01
111) JEM Specimen ID: H25.51.018.11.54.06
   - JEM Patch Tube: PCS4_251223_406_A01
112) JEM Specimen ID: H25.51.018.11.54.07
   - JEM Patch Tube: PCS4_251223_407_A01
113) JEM Specimen ID: QN26.26.003.15.06.01
   - JEM Patch Tube: P9S4_260115_552_A01
114) JEM Specimen ID: C57BL6J-837954.04.09.01
   - JEM Patch Tube: PVS4_251210_451_A01
115) JEM Specimen ID: Drd1a-Cre;Oi9-820240.06.11.01
   - JEM Patch Tube: PXS4_251216_552_A01
116) JEM Specimen ID: Drd1a-Cre;Oi9-820240.06.11.02
   - JEM Patch Tube: PXS4_251216_553_A01
117) JEM Specimen ID: Drd1a-Cre;Oi9-820240.06.11.03
   - JEM Patch Tube: PXS4_251216_554_A01
118) JEM Specimen ID: QF25.26.019.15m.05.01
   - JEM Patch Tube: PCS4_251021_401_A01
119) JEM Specimen ID: QF25.26.019.15m.05.02
   - JEM Patch Tube: PCS4_251021_402_A01
120) JEM Specimen ID: QF25.26.019.15m.05.04
   - JEM Patch Tube: PCS4_251021_403_A01
121) JEM Specimen ID: QN25.26.018.15m.10.01.02
   - JEM Patch Tube: P8S4_251006_351_A01
122) JEM Specimen ID: QN25.26.018.15m.10.01.03
   - JEM Patch Tube: P8S4_251006_352_A01
123) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827267.11.13.02
   - JEM Patch Tube: P8S4_251030_351_A01
124) JEM Specimen ID: QN25.26.018.15m.11.01.01
   - JEM Patch Tube: P4S4_251006_151_A01
125) JEM Specimen ID: QN25.26.018.15m.11.01.02
   - JEM Patch Tube: P4S4_251006_152_A01
126) JEM Specimen ID: QN25.26.018.15m.11.01.03
   - JEM Patch Tube: P4S4_251006_153_A01
127) JEM Specimen ID: QN25.26.018.15m.11.01.04
   - JEM Patch Tube: P4S4_251006_154_A01
128) JEM Specimen ID: QN25.26.018.15m.11.01.05
   - JEM Patch Tube: P4S4_251006_155_A01
129) JEM Specimen ID: H25.51.018.11.02.01
   - JEM Patch Tube: P6S4_251218_402_A01
130) JEM Specimen ID: H25.51.018.11.02.02
   - JEM Patch Tube: P6S4_251218_403_A01
131) JEM Specimen ID: H25.51.018.11.02.04
   - JEM Patch Tube: P6S4_251218_404_A01
132) JEM Specimen ID: H25.51.018.11.02.05
   - JEM Patch Tube: P6S4_251218_405_A01
133) JEM Specimen ID: Scn1a-R613X_B6-830129.06.09.01
   - JEM Patch Tube: P9S4_251016_553_A01
134) JEM Specimen ID: Scn1a-R613X_B6-830129.06.09.04
   - JEM Patch Tube: P9S4_251016_554_A01
135) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841410.16.03.01
   - JEM Patch Tube: PVS4_260115_451_A01
136) JEM Specimen ID: QF25.26.019.15m.04.01
   - JEM Patch Tube: PCS4_251016_551_A01
137) JEM Specimen ID: QF25.26.019.15m.04.03
   - JEM Patch Tube: PCS4_251016_552_A01
138) JEM Specimen ID: QF25.26.022.15m.05.01
   - JEM Patch Tube: PCS4_251022_151_A01
139) JEM Specimen ID: QF25.26.022.15m.05.02
   - JEM Patch Tube: PCS4_251022_152_A01
140) JEM Specimen ID: QF25.26.022.15m.05.03
   - JEM Patch Tube: PCS4_251022_153_A01
141) JEM Specimen ID: QF25.26.022.15m.05.04
   - JEM Patch Tube: PCS4_251022_154_A01
142) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841407.14.03.01
   - JEM Patch Tube: P4S4_260108_151_A01
143) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841407.14.03.02
   - JEM Patch Tube: P4S4_260108_152_A01
144) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841407.14.03.03
   - JEM Patch Tube: P4S4_260108_153_A01
145) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841407.14.03.04
   - JEM Patch Tube: P4S4_260108_154_A01
146) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841407.14.03.05
   - JEM Patch Tube: P4S4_260108_155_A01
147) JEM Specimen ID: QF25.26.028.14d.01.02
   - JEM Patch Tube: PCS4_251202_401_A01
148) JEM Specimen ID: QF25.26.028.14d.01.03
   - JEM Patch Tube: PCS4_251202_402_A01
149) JEM Specimen ID: QF25.26.028.14d.01.04
   - JEM Patch Tube: PCS4_251202_403_A01
150) JEM Specimen ID: QN25.26.020.15m.04.03
   - JEM Patch Tube: PCS4_251021_151_A01
151) JEM Specimen ID: C57BL6J-837955.04.13.01
   - JEM Patch Tube: P9S4_251209_552_A01
152) JEM Specimen ID: QF25.26.021.15m.06.01
   - JEM Patch Tube: PCS4_251015_154_A01
153) JEM Specimen ID: QF25.26.021.15m.06.02
   - JEM Patch Tube: PCS4_251015_155_A01
154) JEM Specimen ID: QF25.26.021.15m.06.03
   - JEM Patch Tube: PCS4_251015_156_A01
155) JEM Specimen ID: QF25.26.023.15m.06.03
   - JEM Patch Tube: PCS4_251111_401_A01
156) JEM Specimen ID: QF25.26.023.15m.06.04
   - JEM Patch Tube: PCS4_251111_402_A01
157) JEM Specimen ID: H26.51.001.11.54.01
   - JEM Patch Tube: PCS4_260121_551_A01
158) JEM Specimen ID: H26.51.001.11.54.02
   - JEM Patch Tube: PCS4_260121_552_A01
159) JEM Specimen ID: H26.51.001.11.54.03
   - JEM Patch Tube: PCS4_260121_553_A01
160) JEM Specimen ID: H26.51.001.11.54.05
   - JEM Patch Tube: PCS4_260121_554_A01
161) JEM Specimen ID: H26.51.001.11.54.07
   - JEM Patch Tube: PCS4_260121_555_A01
162) JEM Specimen ID: H26.51.001.11.54.08
   - JEM Patch Tube: PCS4_260121_556_A01
163) JEM Specimen ID: H26.51.001.11.54.09
   - JEM Patch Tube: PCS4_260121_557_A01
164) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841408.13.13.01
   - JEM Patch Tube: P8S4_260109_351_A01
165) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841408.13.13.02
   - JEM Patch Tube: P8S4_260109_352_A01
166) JEM Specimen ID: Vip-IRES-Cre-835274.14.03.01
   - JEM Patch Tube: P4S4_251205_151_A01
167) JEM Specimen ID: Vip-IRES-Cre-835274.14.03.02
   - JEM Patch Tube: P4S4_251205_152_A01
168) JEM Specimen ID: Vip-IRES-Cre-835274.14.03.03
   - JEM Patch Tube: P4S4_251205_153_A01
169) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841409.05.01.01
   - JEM Patch Tube: P4S4_260113_151_A01
170) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841409.05.01.02
   - JEM Patch Tube: P4S4_260113_152_A01
171) JEM Specimen ID: QN25.26.017.15m.05.01.01
   - JEM Patch Tube: P4S4_250924_153_A01
172) JEM Specimen ID: QN25.26.017.15m.05.01.03
   - JEM Patch Tube: P4S4_250924_154_A01
173) JEM Specimen ID: QN25.26.017.15m.05.01.04
   - JEM Patch Tube: P4S4_250924_155_A01
174) JEM Specimen ID: QN25.26.017.15m.05.01.05
   - JEM Patch Tube: P4S4_250924_156_A01
175) JEM Specimen ID: QN25.26.017.15m.05.01.06
   - JEM Patch Tube: P4S4_250924_157_A01
176) JEM Specimen ID: QN25.26.026.16.10.01
   - JEM Patch Tube: PCS4_251215_151_A01
177) JEM Specimen ID: QN25.26.026.16.10.02
   - JEM Patch Tube: PCS4_251215_152_A01
178) JEM Specimen ID: QN25.26.026.16.10.03
   - JEM Patch Tube: PCS4_251215_153_A01
179) JEM Specimen ID: QN25.26.026.16.10.04
   - JEM Patch Tube: PCS4_251215_154_A01
180) JEM Specimen ID: H25.51.016.11.55.02
   - JEM Patch Tube: PCS4_251028_402_A01
181) JEM Specimen ID: H25.51.016.11.55.03
   - JEM Patch Tube: PCS4_251028_403_A01
182) JEM Specimen ID: H25.51.016.11.55.05
   - JEM Patch Tube: PCS4_251028_404_A01
183) JEM Specimen ID: QF25.26.023.15m.13.03
   - JEM Patch Tube: PCS4_251111_451_A01
184) JEM Specimen ID: H25.51.017.11.52.01
   - JEM Patch Tube: PCS4_251202_351_A01
185) JEM Specimen ID: H25.51.017.11.52.02
   - JEM Patch Tube: PCS4_251202_352_A01
186) JEM Specimen ID: QF25.26.016.15m.13.01.01
   - JEM Patch Tube: PCS4_250924_151_A01
187) JEM Specimen ID: QF25.26.016.15m.13.01.02
   - JEM Patch Tube: PCS4_250924_152_A01
188) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830325.10.03.01
   - JEM Patch Tube: P6S4_251106_401_A01
189) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830325.10.03.02
   - JEM Patch Tube: P6S4_251106_402_A01
190) JEM Specimen ID: Pvalb-IRES-Cre;Ai14-830325.10.03.03
   - JEM Patch Tube: P6S4_251106_403_A01
191) JEM Specimen ID: Sst-IRES-Cre;Ai14-833443.12.13.01
   - JEM Patch Tube: P8S4_251113_351_A01
192) JEM Specimen ID: Sst-IRES-Cre;Ai14-833443.12.13.02
   - JEM Patch Tube: P8S4_251113_352_A01
193) JEM Specimen ID: Drd1a-Cre;Oi9-820240.05.11.02
   - JEM Patch Tube: PXS4_251216_402_A01
194) JEM Specimen ID: C57BL6J-837955.11.13.01
   - JEM Patch Tube: P9S4_251209_551_A01
195) JEM Specimen ID: QF25.26.024.14d.02.01
   - JEM Patch Tube: PCS4_251112_155_A01
196) JEM Specimen ID: QF25.26.024.14d.02.02
   - JEM Patch Tube: PCS4_251112_156_A01
197) JEM Specimen ID: QF25.26.028.14v.08.01
   - JEM Patch Tube: PCS4_251209_351_A01
198) JEM Specimen ID: QF25.26.028.14v.08.02
   - JEM Patch Tube: PCS4_251209_352_A01
199) JEM Specimen ID: H25.51.015.11.54.01.01
   - JEM Patch Tube: PCS4_250925_551_A01
200) JEM Specimen ID: H25.51.015.11.54.01.04
   - JEM Patch Tube: PCS4_250925_552_A01
201) JEM Specimen ID: Slc17a8-IRES2-Cre-neo;Ai14-827263.07.13.01
   - JEM Patch Tube: P8S4_251014_353_A01
202) JEM Specimen ID: H25.51.016.11.04.01
   - JEM Patch Tube: P8S4_251021_351_A01
203) JEM Specimen ID: H25.51.016.11.04.02
   - JEM Patch Tube: P8S4_251021_352_A01
204) JEM Specimen ID: H25.51.016.11.04.03
   - JEM Patch Tube: P8S4_251021_353_A01
205) JEM Specimen ID: H25.51.016.11.04.04
   - JEM Patch Tube: P8S4_251021_354_A01
206) JEM Specimen ID: H25.51.016.11.04.05
   - JEM Patch Tube: P8S4_251021_355_A01
207) JEM Specimen ID: H25.51.016.11.04.06
   - JEM Patch Tube: P8S4_251021_356_A01
208) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841406.04.09.01
   - JEM Patch Tube: P4S4_260107_151_A01
209) JEM Specimen ID: Gad2-IRES-Cre;Ai14-841406.04.09.02
   - JEM Patch Tube: P4S4_260107_152_A01
210) JEM Specimen ID: Drd1a-Cre;Oi9-813175.07.10.01
   - JEM Patch Tube: PXS4_251029_451_A01
211) JEM Specimen ID: Drd1a-Cre;Oi9-813175.07.10.03
   - JEM Patch Tube: PXS4_251029_452_A01
212) JEM Specimen ID: Drd1a-Cre;Oi9-813175.08.10.02
   - JEM Patch Tube: PXS4_251029_353_A01
213) JEM Specimen ID: Drd1a-Cre;Oi9-813175.08.10.03
   - JEM Patch Tube: PXS4_251029_354_A01
214) JEM Specimen ID: QF25.26.016.15m.09.01.01
   - JEM Patch Tube: PCS4_250924_351_A01
215) JEM Specimen ID: QF25.26.016.15m.09.01.02
   - JEM Patch Tube: PCS4_250924_352_A01
216) JEM Specimen ID: QF25.26.016.15m.09.01.03
   - JEM Patch Tube: PCS4_250924_353_A01
217) JEM Specimen ID: QN26.26.004.15.06.01
   - JEM Patch Tube: P6S4_260120_404_A01
218) JEM Specimen ID: QN26.26.004.15.06.02
   - JEM Patch Tube: P6S4_260120_405_A01
219) JEM Specimen ID: QN26.26.004.15.06.03
   - JEM Patch Tube: P6S4_260120_406_A01